# POST http://127.0.0.1:3000/api/v1/user/register
# Content-Type: application/json

# {
#     "NickName": "amor",
#     "UserName": "luoyangc",
#     "password": "12345678",
#     "password_confirm": "12345678"
# }

# POST http://127.0.0.1:3000/api/v1/user/login
# Content-Type: application/json

# {
#     "user_name": "luoyangc",
#     "password": "12345678"
# }

GET http://127.0.0.1:3000/api/v1/user/me HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjEsIlVzZXJOYW1lIjoibHVveWFuZ2MiLCJTdGF0dXMiOiJhY3RpdmUiLCJBdmF0YXIiOiIiLCJleHAiOjE1NjUxMDUyMjQsImlzcyI6Imx1b3lhbmdjIiwibmJmIjoxNTY1MTAwNjI0fQ.CQ4VEeWWpFQmtD0m6_u92BoeTd6AuiXY5eGsDSWNhOU